### ISSUE TITLE
Failed to fetch properties during pod restart

### ISSUE THREAD

**Issue by zhanggbj** [SUSE/configgin#72] opened 2018-05-09 05:46 UTC
**Background**
api pod will fetch property in cc_uploader by BOSH links, like here. https://github.com/cloudfoundry/capi-release/blob/develop/jobs/cloud_controller_ng/templates/cloud_controller_ng.yml.erb#L360
(Just take api as an example, actually this issue also happened with other components.)

**Description**
This works well during the first deployment, but when we inject a sidecar container into the api pod, it will trigger a pod recreate, `sometimes` there's one error occurs like below

```
+ bash /opt/fissile/startup/scripts/forward_logfiles.sh
+ configgin --jobs /opt/fissile/job_config.json --env2conf /opt/fissile/env2conf.yml
Resolving link cc_uploader via service {"role"=>"cc-uploader", "job"=>"cc_uploader"}
/usr/local/rvm/gems/ruby-2.3.5/gems/bosh-template-2.0.0/lib/bosh/template/evaluation_link.rb:30:in `p': Can't find property '["internal_hostname"]' (Bosh::Template::UnknownProperty)
	from /var/vcap/jobs-src/cloud_controller_ng/templates/cloud_controller_api.yml.erb:445:in `block in get_binding'
	from /usr/local/rvm/gems/ruby-2.3.5/gems/bosh-template-2.0.0/lib/bosh/template/evaluation_context.rb:152:in `if_link'
	from /var/vcap/jobs-src/cloud_controller_ng/templates/cloud_controller_api.yml.erb:443:in `get_binding'
	from /usr/local/rvm/rubies/ruby-2.3.5/lib/ruby/2.3.0/erb.rb:864:in `eval'
	from /usr/local/rvm/rubies/ruby-2.3.5/lib/ruby/2.3.0/erb.rb:864:in `result'
	from /usr/local/rvm/gems/ruby-2.3.5/gems/configgin-0.14.1/lib/job.rb:57:in `generate'
	from /usr/local/rvm/gems/ruby-2.3.5/gems/configgin-0.14.1/bin/configgin:79:in `block (2 levels) in <top (required)>'
	from /usr/local/rvm/gems/ruby-2.3.5/gems/configgin-0.14.1/bin/configgin:78:in `each'
	from /usr/local/rvm/gems/ruby-2.3.5/gems/configgin-0.14.1/bin/configgin:78:in `block in <top (required)>'
	from /usr/local/rvm/gems/ruby-2.3.5/gems/configgin-0.14.1/bin/configgin:75:in `each'
	from /usr/local/rvm/gems/ruby-2.3.5/gems/configgin-0.14.1/bin/configgin:75:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.3.5/bin/configgin:23:in `load'
	from /usr/local/rvm/gems/ruby-2.3.5/bin/configgin:23:in `<main>'
	from /usr/local/rvm/gems/ruby-2.3.5/bin/ruby_executable_hooks:15:in `eval'
	from /usr/local/rvm/gems/ruby-2.3.5/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by qu1queee** [comment] 2018-06-25 13:46
Hi,

Together with @HeavyWombat we dig into this issue, cause was blocking us for moving forward with multiple colocated-containers per pod.

We think we find the root cause, and we will like some feedback on that. 

There seems to be a race condition between the _N_ `configgin`s per container, where each wants to patch the POD configuration to update the exported properties via `skiff-exported-properties` in `metadata.annotation`. This only happens for properties that are part of bosh links.

To be more precise, this [piece of code](https://github.com/SUSE/configgin/blob/master/bin/configgin#L69-L73) seems to be setting the exported properties in a not consistent way, depending on which pod container comes up first. 

For example, if we have 2 `doppler` pods, we can prove the above:
```
$ kubectl -n cf get pod doppler-0 -o json | jq -r '.metadata.annotations["skiff-exported-properties"]'
{"global-properties":{},"logstash-forwarder":{}}
```

```
$ kubectl -n cf get pod doppler-1 -o json | jq -r '.metadata.annotations["skiff-exported-properties"]'
{"doppler":{"doppler":{"grpc_port":8082}},"global-properties":{},"metron_agent":{"metron_agent":{"listening_address":"127.0.0.1","listening_port":3457}}}
```

As shown in the logs, having a doppler instance without the exported properties, will cause a POD that consumes these properties, to fail, e.g.:

```
+ configgin --jobs /opt/fissile/job_config.json --env2conf /opt/fissile/env2conf.yml
Resolving link doppler via statefulset {"role"=>"doppler", "job"=>"doppler"}
/usr/local/rvm/gems/ruby-2.3.5/gems/bosh-template-2.1.0/lib/bosh/template/evaluation_link.rb:30:in `p': Can't find property '["doppler.grpc_port"]' (Bosh::Template::UnknownProperty)
	from /var/vcap/jobs-src/reverse_log_proxy/templates/environment.sh.erb:5:in `block (2 levels) in get_binding'
	from /var/vcap/jobs-src/reverse_log_proxy/templates/environment.sh.erb:4:in `map'
	from /var/vcap/jobs-src/reverse_log_proxy/templates/environment.sh.erb:4:in `block in get_binding'
	from /usr/local/rvm/gems/ruby-2.3.5/gems/bosh-template-2.1.0/lib/bosh/template/evaluation_context.rb:131:in `if_link'
	from /var/vcap/jobs-src/reverse_log_proxy/templates/environment.sh.erb:3:in `get_binding'
	from /usr/local/rvm/rubies/ruby-2.3.5/lib/ruby/2.3.0/erb.rb:864:in `eval'
	from /usr/local/rvm/rubies/ruby-2.3.5/lib/ruby/2.3.0/erb.rb:864:in `result'
	from /usr/local/rvm/gems/ruby-2.3.5/gems/configgin-0.15.0/lib/job.rb:70:in `generate'
	from /usr/local/rvm/gems/ruby-2.3.5/gems/configgin-0.15.0/bin/configgin:79:in `block (2 levels) in <top (required)>'
	from /usr/local/rvm/gems/ruby-2.3.5/gems/configgin-0.15.0/bin/configgin:78:in `each'
	from /usr/local/rvm/gems/ruby-2.3.5/gems/configgin-0.15.0/bin/configgin:78:in `block in <top (required)>'
	from /usr/local/rvm/gems/ruby-2.3.5/gems/configgin-0.15.0/bin/configgin:75:in `each'
	from /usr/local/rvm/gems/ruby-2.3.5/gems/configgin-0.15.0/bin/configgin:75:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.3.5/bin/configgin:23:in `load'
	from /usr/local/rvm/gems/ruby-2.3.5/bin/configgin:23:in `<main>'
	from /usr/local/rvm/gems/ruby-2.3.5/bin/ruby_executable_hooks:15:in `eval'
	from /usr/local/rvm/gems/ruby-2.3.5/bin/ruby_executable_hooks:15:in `<main>'
```

So far we came up with only one possible solution for that and would like to get in touch with you to discuss other possibilities or ideas. One fix would be to not simply patch the POD YAML, but to read the POD YAML first in order to merge any potential existing `skiff-exported-properties` with the ones of the pod container which is currently ramping up with configgin.

**Comment by viovanov** [comment] 2018-06-25 15:06
ping @mook-as

**Comment by mook-as** [comment] 2018-06-25 16:00
Ah, because that code was designed in a single-container world, and assumed patching the pod is fine because nobody else is patching it.

Then yes, reading before writing could work, but we'll need to worry about races (as in, container 1 reads, container 2 reads + writes, container 1 overwrites).  Given that it's patching things to be empty, it's _probably_ not doing a [merge](https://kubernetes.io/docs/tasks/run-application/update-api-object-kubectl-patch/).  I assume it isn't possible for the "main" container to wait for colocated containers (assuming it can grab a list of them)? Will the main container need values from the colocated containers (e.g. for things that provide metron)?  As in, I wonder if we might need to 1) have the colocated containers write to other annotations (`skiff-exported-properties-metron` or something like that), 2) have the main container wait (like it currently does for the other pods) until all the expected colocated containers have written their properties, and 3) do the existing thing, and add the `skiff-exported-properties` with the merged result.  Thoughts?

**Comment by viovanov** [comment] 2018-06-26 09:15
@mook-as I think each container writing to it's own annotation is cleanest.
I assume discovering all the written annotations is not an issue?

**Comment by viovanov** [comment] 2018-06-26 10:08
@qu1queee are you going to implement a fix like that? 
Making sure we're not duplicating work.

**Comment by qu1queee** [comment] 2018-06-26 10:57
yes, we will work on the per container annotation approach. @viovanov

**Comment by qu1queee** [comment] 2018-07-23 09:49
Can we close this issue?

**Comment by mook-as** [comment] 2018-07-23 16:12
Yeah, I think this was fixed by the referenced PRs.  Please ping (or directly reopen) if that isn't the case.

**Closed by mook-as** 2018-07-23 16:12 UTC
